apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 5  # Five client instances
  selector:
    matchLabels:
      app: distributed-app
      role: client
  template:
    metadata:
      labels:
        app: distributed-app
        role: client
    spec:
      containers:
      - name: client
        image: my-distributed-app
        command: ["python3", "client.py"]
        env:
        - name: SERVER_URL
          value: "http://server-service:8000"  # Kubernetes DNS name for servers
