apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1  #  server instances
  selector:
    matchLabels:
      app: distributed-app
      role: server
  template:
    metadata:
      labels:
        app: distributed-app
        role: server
    spec:
      containers:
      - name: server
        image: my-distributed-app
        imagePullPolicy: Never  # This tells Kubernetes to use local image
        command: ["python3", "server.py"]
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: distributed-app
    role: server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
